# Generated by Django 3.0.5 on 2020-05-03 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20200503_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='useremail',
            new_name='user_email',
        ),
    ]
